[package]
name = "galactic"
version = "0.1.1"
authors = ["jRimbault <jacques.rimbault@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json", "cookies"] }
structopt = "0.3.17"
